######################################################################
# Automatically generated by qmake (2.01a) mar may 24 20:42:32 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += common.h
SOURCES += common.cpp serial.cpp
